version: '3.4'

services:
  elasticsearchdemo:
    image: ${DOCKER_REGISTRY-}elasticsearchdemo
    ports:
      - 6464:80
    build:
      context: .
      dockerfile: ElasticSearchDemo/Dockerfile
    networks:
       - elasticnetwork
  elasticsearch:
    container_name: es01
    image: docker.elastic.co/elasticsearch/elasticsearch:8.3.3
    ports:
      - 9200:9200
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/datafile
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
      - xpack.security.enabled=false
    networks:
      - elasticnetwork

  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:8.3.3
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch
    environment:
       ELASTICSEARCH_URL: http://es01:9200
       ELASTICSEARCH_HOSTS: http://es01:9200
    networks:
      - elasticnetwork
networks:
  elasticnetwork:
    driver: bridge

volumes:
  elasticsearch-data:
   driver: local